name: Build GDExtension
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout godot-cpp
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot-cpp
          path: godot-cpp
 
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev
      
      - name: Build godot-cpp ${{ env.BUILD_TARGET }}
        run: |
          pushd godot-cpp
          scons target=debug
          popd

      - name: Checkout GDExtension_delaunator
        uses: actions/checkout@v3
        with:
          path: godot-cpp/gdextension-delaunator

      - name: build delaunator Linux ${{ env.BUILD_TARGET }}
        run: |
          pushd godot-cpp/gdextension-delaunator
          scons platform=linux   target=${{ env.BUILD_TARGET }} bits=64 target_name="gddelaunator" target_path="./bin/"
          popd

      - name: build delaunator Windows ${{ env.BUILD_TARGET }}
        continue-on-error: true
        run: |
          pushd godot-cpp/gdextension-delaunator
          scons platform=windows   target=${{ env.BUILD_TARGET }} bits=64 target_name="gddelaunator" target_path="./bin/"
          popd        

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: gdextension-delaunator
          path: godot-cpp/gdextension-delaunator/bin         
